-- MySQL Script generated by MySQL Workbench
-- jue 16 jun 2016 11:14:09 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mistlogic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mistlogic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mistlogic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mistlogic` ;

-- -----------------------------------------------------
-- Table `mistlogic`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mistlogic`.`equipo` (
  `no_serie` VARCHAR(10) NOT NULL,
  `manual` TINYINT(1) NOT NULL,
  `automatico` TINYINT(1) NOT NULL,
  `auto_on` TINYINT(1) NOT NULL,
  `auto_off` TINYINT(1) NOT NULL,
  `nivel_bajo` TINYINT(1) NOT NULL,
  `nivel_min` FLOAT NOT NULL,
  `nivel_max` FLOAT NOT NULL,
  `server_ip` VARCHAR(15) NOT NULL,
  `server_port` VARCHAR(6) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`no_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mistlogic`.`set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mistlogic`.`set` (
  `id_set` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_set`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mistlogic`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mistlogic`.`programa` (
  `id_prog` INT NOT NULL AUTO_INCREMENT,
  `id_set` INT NOT NULL,
  `tipo` TINYINT(1) NULL,
  `dias` INT NULL,
  `hora_ini` TIME NULL,
  `hora_fin` TIME NULL,
  `t_espera` INT NULL,
  `t_aspersion` INT NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`id_prog`),
  INDEX `fk_programa_set_idx` (`id_set` ASC),
  CONSTRAINT `fk_programa_set`
    FOREIGN KEY (`id_set`)
    REFERENCES `mistlogic`.`set` (`id_set`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mistlogic`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mistlogic`.`log` (
  `id_log` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
